# bsGangs v1.0
# by @VedCodee (Dev) & @BinaryCodee (Graphic)
#
# Database Type
#
# SQLITE
# or
# MYSQL
#

license: "null"

placeholders:
  active: true
  no_team: "None"
  no_team_leaderboard_name: "None"
  no_team_leaderboard_stats: "-"
team:
  length:
    max: 10
    min: 3
  badWord:
    - "suck"
    - "dick"
    - "bitch"
  players:
    infinite: false
    max: 4
  pvp: false # If you change this, you must reload the server
  saveDelay: 10 # is in second
  points:
    death: 2 # remove 2 points
    kill: 1 # add 1 point
rank:
  leader: "&8[&cLeader&8]"
  moderator: "&8[&cModerator&8]"
  member: "&8[&7Member&8]"
use: "SQLITE"
database:
  sqlite: "bsGangs.db"
  mysql:
    host: "localhost"
    port: "3306"
    database: "bsGang"
    username: "root"
    password: ""